HFFBaseBundle_homepage:
    pattern:  /
    defaults: { _controller: HFFBaseBundle:Page:index }
    requirements:
        _method:  GET

HFFBaseBundle_about:
    pattern:  /about
    defaults: { _controller: HFFBaseBundle:Page:about }
    requirements:
        _method:  GET
