HFFBaseBundle_homepage:
    pattern:  /
    defaults: { _controller: HFFBaseBundle:Page:index }
    requirements:
        _method:  GET

HFFBaseBundle_about:
    pattern:  /about
    defaults: { _controller: HFFBaseBundle:Page:about }
    requirements:
        _method:  GET

HFFBaseBundle_contact:
    pattern:  /contact
    defaults: { _controller: HFFBaseBundle:Page:contact }
    requirements:
        _method:  GET

HFFBaseBundle_register_project:
    pattern:  /register-project
    defaults: { _controller: HFFBaseBundle:Page:register_project }
    requirements:
        _method:  GET
