parameters:
#    hff_base.example.class: HFF\BaseBundle\Example

services:
#    hff_base.example:
#        class: %hff_base.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
